// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * RunEvent representa um evento lido do JSONL.
 */
export class RunEvent {
    /**
     * Creates a new RunEvent instance.
     * @param {Partial<RunEvent>} [$$source = {}] - The source object to create the RunEvent.
     */
    constructor($$source = {}) {
        if (!("cursor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cursor"] = 0;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["timestamp"] = null;
        }
        if (!("run_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["run_id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["node_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["instance_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["attempt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunEvent}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("path" in $$parsedSource) {
            $$parsedSource["path"] = $$createField6_0($$parsedSource["path"]);
        }
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField8_0($$parsedSource["data"]);
        }
        return new RunEvent(/** @type {Partial<RunEvent>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
