// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * @readonly
 * @enum {string}
 */
export const RunStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RunCreated: "created",
    RunValidating: "validating",
    RunPlanned: "planned",
    RunRunning: "running",
    RunPaused: "paused",
    RunSuccess: "success",
    RunFailed: "failed",
    RunCancelled: "cancelled",
};
