# AgentFlow Homebrew Formula
#
# This formula installs the agentflow CLI and agentflowd daemon from published
# GitHub Release tarballs. The archive naming follows the release workflow:
#   agentflow-<version>-<os>-<arch>.tar.gz
#
# Before publishing a release, update the version and replace each sha256
# placeholder with the real checksum from SHA256SUMS.txt generated by the
# release pipeline.
#
# The formula installs both binaries because agentflow run uses agentflowd
# by default. Users who only want the foreground runner (-it) still benefit
# from having the daemon available.

class Agentflow < Formula
  desc "YAML workflows for local coding agents"
  homepage "https://github.com/diasYuri/agentflow"
  version "0.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/diasYuri/agentflow/releases/download/v#{version}/agentflow-v#{version}-darwin-arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/diasYuri/agentflow/releases/download/v#{version}/agentflow-v#{version}-darwin-amd64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/diasYuri/agentflow/releases/download/v#{version}/agentflow-v#{version}-linux-arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/diasYuri/agentflow/releases/download/v#{version}/agentflow-v#{version}-linux-amd64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bundle = Dir["agentflow-*"].first
    bin.install "#{bundle}/agentflow"
    bin.install "#{bundle}/agentflowd"
    generate_completions_from_executable(bin/"agentflow", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentflow version")
    system bin/"agentflow", "doctor"
  end
end
