// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as run$0 from "../../core/run/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runtime$0 from "../runtime/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * AppSettings persistem preferencias locais do desktop.
 */
export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("workspacePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workspacePath"] = "";
        }
        if (!("recentFiles" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["recentFiles"] = [];
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("codexPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["codexPath"] = "";
        }
        if (!("claudePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["claudePath"] = "";
        }
        if (!("piPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["piPath"] = "";
        }
        if (!("logFormat" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logFormat"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recentFiles" in $$parsedSource) {
            $$parsedSource["recentFiles"] = $$createField1_0($$parsedSource["recentFiles"]);
        }
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

/**
 * ArtifactInfo resume um artefato.
 */
export class ArtifactInfo {
    /**
     * Creates a new ArtifactInfo instance.
     * @param {Partial<ArtifactInfo>} [$$source = {}] - The source object to create the ArtifactInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["content_type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | undefined}
             */
            this["modified_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtifactInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArtifactInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArtifactInfo(/** @type {Partial<ArtifactInfo>} */($$parsedSource));
    }
}

/**
 * ArtifactResponse retorna conteudo de um artefato.
 */
export class ArtifactResponse {
    /**
     * Creates a new ArtifactResponse instance.
     * @param {Partial<ArtifactResponse>} [$$source = {}] - The source object to create the ArtifactResponse.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["content_type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["encoding"] = undefined;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtifactResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArtifactResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArtifactResponse(/** @type {Partial<ArtifactResponse>} */($$parsedSource));
    }
}

/**
 * ArtifactsResponse retorna artefatos de uma run.
 */
export class ArtifactsResponse {
    /**
     * Creates a new ArtifactsResponse instance.
     * @param {Partial<ArtifactsResponse>} [$$source = {}] - The source object to create the ArtifactsResponse.
     */
    constructor($$source = {}) {
        if (!("run_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["run_id"] = "";
        }
        if (!("artifacts" in $$source)) {
            /**
             * @member
             * @type {ArtifactInfo[]}
             */
            this["artifacts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtifactsResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArtifactsResponse}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artifacts" in $$parsedSource) {
            $$parsedSource["artifacts"] = $$createField1_0($$parsedSource["artifacts"]);
        }
        return new ArtifactsResponse(/** @type {Partial<ArtifactsResponse>} */($$parsedSource));
    }
}

/**
 * DesktopError representa um erro normalizado para consumo pela UI.
 */
export class DesktopError {
    /**
     * Creates a new DesktopError instance.
     * @param {Partial<DesktopError>} [$$source = {}] - The source object to create the DesktopError.
     */
    constructor($$source = {}) {
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["context"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopError instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DesktopError}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopError(/** @type {Partial<DesktopError>} */($$parsedSource));
    }
}

/**
 * DryRunResult retorna o plano de execucao sem executar.
 */
export class DryRunResult {
    /**
     * Creates a new DryRunResult instance.
     * @param {Partial<DryRunResult>} [$$source = {}] - The source object to create the DryRunResult.
     */
    constructor($$source = {}) {
        if (!("workflow" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workflow"] = "";
        }
        if (!("inputs" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["inputs"] = {};
        }
        if (!("order" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["order"] = [];
        }
        if (!("nodes" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: NodePlan }}
             */
            this["nodes"] = {};
        }
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valid"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DesktopError[] | undefined}
             */
            this["errors"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DryRunResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DryRunResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType5;
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputs" in $$parsedSource) {
            $$parsedSource["inputs"] = $$createField1_0($$parsedSource["inputs"]);
        }
        if ("order" in $$parsedSource) {
            $$parsedSource["order"] = $$createField2_0($$parsedSource["order"]);
        }
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField3_0($$parsedSource["nodes"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField5_0($$parsedSource["errors"]);
        }
        return new DryRunResult(/** @type {Partial<DryRunResult>} */($$parsedSource));
    }
}

/**
 * EventsResponse retorna eventos paginados.
 */
export class EventsResponse {
    /**
     * Creates a new EventsResponse instance.
     * @param {Partial<EventsResponse>} [$$source = {}] - The source object to create the EventsResponse.
     */
    constructor($$source = {}) {
        if (!("run_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["run_id"] = "";
        }
        if (!("events" in $$source)) {
            /**
             * @member
             * @type {runtime$0.RunEvent[]}
             */
            this["events"] = [];
        }
        if (!("next_cursor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["next_cursor"] = 0;
        }
        if (!("has_more" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventsResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EventsResponse}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField1_0($$parsedSource["events"]);
        }
        return new EventsResponse(/** @type {Partial<EventsResponse>} */($$parsedSource));
    }
}

/**
 * GraphResult retorna o grafo Mermaid de um workflow.
 */
export class GraphResult {
    /**
     * Creates a new GraphResult instance.
     * @param {Partial<GraphResult>} [$$source = {}] - The source object to create the GraphResult.
     */
    constructor($$source = {}) {
        if (!("mermaid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mermaid"] = "";
        }
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valid"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DesktopError[] | undefined}
             */
            this["errors"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GraphResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField2_0($$parsedSource["errors"]);
        }
        return new GraphResult(/** @type {Partial<GraphResult>} */($$parsedSource));
    }
}

/**
 * InputDocument descreve uma entrada de workflow.
 */
export class InputDocument {
    /**
     * Creates a new InputDocument instance.
     * @param {Partial<InputDocument>} [$$source = {}] - The source object to create the InputDocument.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["required"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["default"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InputDocument instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InputDocument}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InputDocument(/** @type {Partial<InputDocument>} */($$parsedSource));
    }
}

/**
 * ListRunsResponse lista execucoes.
 */
export class ListRunsResponse {
    /**
     * Creates a new ListRunsResponse instance.
     * @param {Partial<ListRunsResponse>} [$$source = {}] - The source object to create the ListRunsResponse.
     */
    constructor($$source = {}) {
        if (!("runs" in $$source)) {
            /**
             * @member
             * @type {RunSummary[]}
             */
            this["runs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListRunsResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListRunsResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("runs" in $$parsedSource) {
            $$parsedSource["runs"] = $$createField0_0($$parsedSource["runs"]);
        }
        return new ListRunsResponse(/** @type {Partial<ListRunsResponse>} */($$parsedSource));
    }
}

/**
 * LoadedWorkflow representa um workflow carregado para edicao/inspecao.
 */
export class LoadedWorkflow {
    /**
     * Creates a new LoadedWorkflow instance.
     * @param {Partial<LoadedWorkflow>} [$$source = {}] - The source object to create the LoadedWorkflow.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("inputs" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: InputDocument }}
             */
            this["inputs"] = {};
        }
        if (!("nodes" in $$source)) {
            /**
             * @member
             * @type {NodeSummary[]}
             */
            this["nodes"] = [];
        }
        if (!("sourcePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourcePath"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["rawYaml"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadedWorkflow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoadedWorkflow}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType13;
        const $$createField4_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputs" in $$parsedSource) {
            $$parsedSource["inputs"] = $$createField3_0($$parsedSource["inputs"]);
        }
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField4_0($$parsedSource["nodes"]);
        }
        return new LoadedWorkflow(/** @type {Partial<LoadedWorkflow>} */($$parsedSource));
    }
}

/**
 * LogsResponse retorna linhas de log (events.jsonl).
 */
export class LogsResponse {
    /**
     * Creates a new LogsResponse instance.
     * @param {Partial<LogsResponse>} [$$source = {}] - The source object to create the LogsResponse.
     */
    constructor($$source = {}) {
        if (!("run_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["run_id"] = "";
        }
        if (!("lines" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogsResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogsResponse}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField1_0($$parsedSource["lines"]);
        }
        return new LogsResponse(/** @type {Partial<LogsResponse>} */($$parsedSource));
    }
}

/**
 * NodePlan resume um no dentro de um plano de execucao.
 */
export class NodePlan {
    /**
     * Creates a new NodePlan instance.
     * @param {Partial<NodePlan>} [$$source = {}] - The source object to create the NodePlan.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("dependencies" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["dependencies"] = [];
        }
        if (!("dependents" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["dependents"] = [];
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodePlan instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NodePlan}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dependencies" in $$parsedSource) {
            $$parsedSource["dependencies"] = $$createField1_0($$parsedSource["dependencies"]);
        }
        if ("dependents" in $$parsedSource) {
            $$parsedSource["dependents"] = $$createField2_0($$parsedSource["dependents"]);
        }
        return new NodePlan(/** @type {Partial<NodePlan>} */($$parsedSource));
    }
}

/**
 * NodeResponse retorna instancias de um no.
 */
export class NodeResponse {
    /**
     * Creates a new NodeResponse instance.
     * @param {Partial<NodeResponse>} [$$source = {}] - The source object to create the NodeResponse.
     */
    constructor($$source = {}) {
        if (!("run_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["run_id"] = "";
        }
        if (!("node_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["node_id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {NodeResultDTO[] | undefined}
             */
            this["instances"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NodeResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("instances" in $$parsedSource) {
            $$parsedSource["instances"] = $$createField2_0($$parsedSource["instances"]);
        }
        return new NodeResponse(/** @type {Partial<NodeResponse>} */($$parsedSource));
    }
}

/**
 * NodeResultDTO representa resultado de um no.
 */
export class NodeResultDTO {
    /**
     * Creates a new NodeResultDTO instance.
     * @param {Partial<NodeResultDTO>} [$$source = {}] - The source object to create the NodeResultDTO.
     */
    constructor($$source = {}) {
        if (!("node_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["node_id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["instance_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["index"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["output"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any[] | undefined}
             */
            this["outputs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["stdout"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["stderr"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["exit_code"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["duration_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["attempts"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeResultDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NodeResultDTO}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField6_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("path" in $$parsedSource) {
            $$parsedSource["path"] = $$createField2_0($$parsedSource["path"]);
        }
        if ("outputs" in $$parsedSource) {
            $$parsedSource["outputs"] = $$createField6_0($$parsedSource["outputs"]);
        }
        return new NodeResultDTO(/** @type {Partial<NodeResultDTO>} */($$parsedSource));
    }
}

/**
 * NodeSummary resume um no do workflow.
 */
export class NodeSummary {
    /**
     * Creates a new NodeSummary instance.
     * @param {Partial<NodeSummary>} [$$source = {}] - The source object to create the NodeSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["dependsOn"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NodeSummary}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dependsOn" in $$parsedSource) {
            $$parsedSource["dependsOn"] = $$createField2_0($$parsedSource["dependsOn"]);
        }
        return new NodeSummary(/** @type {Partial<NodeSummary>} */($$parsedSource));
    }
}

/**
 * NodesResponse retorna resultados de nos.
 */
export class NodesResponse {
    /**
     * Creates a new NodesResponse instance.
     * @param {Partial<NodesResponse>} [$$source = {}] - The source object to create the NodesResponse.
     */
    constructor($$source = {}) {
        if (!("run_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["run_id"] = "";
        }
        if (!("nodes" in $$source)) {
            /**
             * @member
             * @type {NodeResultDTO[]}
             */
            this["nodes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodesResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NodesResponse}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField1_0($$parsedSource["nodes"]);
        }
        return new NodesResponse(/** @type {Partial<NodesResponse>} */($$parsedSource));
    }
}

/**
 * PlanResponse retorna o plano da run.
 */
export class PlanResponse {
    /**
     * Creates a new PlanResponse instance.
     * @param {Partial<PlanResponse>} [$$source = {}] - The source object to create the PlanResponse.
     */
    constructor($$source = {}) {
        if (!("run_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["run_id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workflow"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["metadata"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["normalized"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["plan"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlanResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField2_0($$parsedSource["metadata"]);
        }
        if ("normalized" in $$parsedSource) {
            $$parsedSource["normalized"] = $$createField3_0($$parsedSource["normalized"]);
        }
        if ("plan" in $$parsedSource) {
            $$parsedSource["plan"] = $$createField4_0($$parsedSource["plan"]);
        }
        return new PlanResponse(/** @type {Partial<PlanResponse>} */($$parsedSource));
    }
}

/**
 * RunSummary resume uma execucao de workflow.
 */
export class RunSummary {
    /**
     * Creates a new RunSummary instance.
     * @param {Partial<RunSummary>} [$$source = {}] - The source object to create the RunSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("workflow" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workflow"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {run$0.RunStatus}
             */
            this["status"] = run$0.RunStatus.$zero;
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["started_at"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | undefined}
             */
            this["finished_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["current_step"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["completed_steps"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["pending_steps"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["total_steps"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunSummary}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("completed_steps" in $$parsedSource) {
            $$parsedSource["completed_steps"] = $$createField7_0($$parsedSource["completed_steps"]);
        }
        if ("pending_steps" in $$parsedSource) {
            $$parsedSource["pending_steps"] = $$createField8_0($$parsedSource["pending_steps"]);
        }
        return new RunSummary(/** @type {Partial<RunSummary>} */($$parsedSource));
    }
}

/**
 * RunWorkflowRequest inicia uma execucao de workflow.
 */
export class RunWorkflowRequest {
    /**
     * Creates a new RunWorkflowRequest instance.
     * @param {Partial<RunWorkflowRequest>} [$$source = {}] - The source object to create the RunWorkflowRequest.
     */
    constructor($$source = {}) {
        if (!("workflow_ref" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workflow_ref"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["inputs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["vars"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["max_concurrency"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["working_dir"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunWorkflowRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunWorkflowRequest}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputs" in $$parsedSource) {
            $$parsedSource["inputs"] = $$createField1_0($$parsedSource["inputs"]);
        }
        if ("vars" in $$parsedSource) {
            $$parsedSource["vars"] = $$createField2_0($$parsedSource["vars"]);
        }
        return new RunWorkflowRequest(/** @type {Partial<RunWorkflowRequest>} */($$parsedSource));
    }
}

/**
 * ValidationResult retorna o resultado da validacao de um workflow.
 */
export class ValidationResult {
    /**
     * Creates a new ValidationResult instance.
     * @param {Partial<ValidationResult>} [$$source = {}] - The source object to create the ValidationResult.
     */
    constructor($$source = {}) {
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valid"] = false;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("nodeCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["nodeCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DesktopError[] | undefined}
             */
            this["errors"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ValidationResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new ValidationResult(/** @type {Partial<ValidationResult>} */($$parsedSource));
    }
}

/**
 * WorkflowSummary resume um workflow disponivel para listagem.
 */
export class WorkflowSummary {
    /**
     * Creates a new WorkflowSummary instance.
     * @param {Partial<WorkflowSummary>} [$$source = {}] - The source object to create the WorkflowSummary.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkflowSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkflowSummary(/** @type {Partial<WorkflowSummary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ArtifactInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = NodePlan.createFrom;
const $$createType5 = $Create.Map($Create.Any, $$createType4);
const $$createType6 = DesktopError.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = runtime$0.RunEvent.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = RunSummary.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = InputDocument.createFrom;
const $$createType13 = $Create.Map($Create.Any, $$createType12);
const $$createType14 = NodeSummary.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = NodeResultDTO.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $Create.Array($Create.Any);
