// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DesktopService expoe metodos ao frontend via Wails v3 bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as adapter$0 from "../adapter/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelRun cancela uma execucao ativa.
 * @param {string} runID
 * @returns {$CancellablePromise<adapter$0.RunSummary>}
 */
export function CancelRun(runID) {
    return $Call.ByID(2509854971, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DryRunWorkflow executa dry-run de um workflow.
 * @param {string} path
 * @param {{ [_ in string]?: any }} inputs
 * @param {{ [_ in string]?: any }} vars
 * @param {number} maxConcurrency
 * @param {string} workingDir
 * @returns {$CancellablePromise<adapter$0.DryRunResult>}
 */
export function DryRunWorkflow(path, inputs, vars, maxConcurrency, workingDir) {
    return $Call.ByID(2583879111, path, inputs, vars, maxConcurrency, workingDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GenerateGraph gera o grafo Mermaid de um workflow.
 * @param {string} path
 * @returns {$CancellablePromise<adapter$0.GraphResult>}
 */
export function GenerateGraph(path) {
    return $Call.ByID(595569741, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetAppSettings retorna as configuracoes locais.
 * @returns {$CancellablePromise<adapter$0.AppSettings>}
 */
export function GetAppSettings() {
    return $Call.ByID(972060370).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetRun retorna uma execucao especifica.
 * @param {string} runID
 * @returns {$CancellablePromise<adapter$0.RunSummary>}
 */
export function GetRun(runID) {
    return $Call.ByID(842898233, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetRunArtifact retorna conteudo de um artefato.
 * @param {string} runID
 * @param {string} artifactID
 * @returns {$CancellablePromise<adapter$0.ArtifactResponse>}
 */
export function GetRunArtifact(runID, artifactID) {
    return $Call.ByID(2255375615, runID, artifactID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetRunArtifacts lista artefatos de uma run.
 * @param {string} runID
 * @returns {$CancellablePromise<adapter$0.ArtifactsResponse>}
 */
export function GetRunArtifacts(runID) {
    return $Call.ByID(732069988, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetRunEvents retorna eventos paginados de uma run.
 * @param {string} runID
 * @param {number} cursor
 * @param {number} limit
 * @returns {$CancellablePromise<adapter$0.EventsResponse>}
 */
export function GetRunEvents(runID, cursor, limit) {
    return $Call.ByID(1309699360, runID, cursor, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetRunLogs retorna linhas de log (events.jsonl).
 * @param {string} runID
 * @returns {$CancellablePromise<adapter$0.LogsResponse>}
 */
export function GetRunLogs(runID) {
    return $Call.ByID(4018705698, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetRunNode retorna instancias de um no especifico.
 * @param {string} runID
 * @param {string} nodeID
 * @returns {$CancellablePromise<adapter$0.NodeResponse>}
 */
export function GetRunNode(runID, nodeID) {
    return $Call.ByID(3391098529, runID, nodeID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetRunNodes lista resultados de nos.
 * @param {string} runID
 * @returns {$CancellablePromise<adapter$0.NodesResponse>}
 */
export function GetRunNodes(runID) {
    return $Call.ByID(41374870, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetRunPlan retorna metadados e plano de uma run.
 * @param {string} runID
 * @returns {$CancellablePromise<adapter$0.PlanResponse>}
 */
export function GetRunPlan(runID) {
    return $Call.ByID(2617265798, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * Greet e um metodo de exemplo que sera removido em planos futuros.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(203791073, name);
}

/**
 * Health retorna um status basico para validar a comunicacao Go <-> UI.
 * @returns {$CancellablePromise<$models.HealthResponse>}
 */
export function Health() {
    return $Call.ByID(3021161094).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * ListRuns lista execucoes ativas e persistidas.
 * @returns {$CancellablePromise<adapter$0.ListRunsResponse>}
 */
export function ListRuns() {
    return $Call.ByID(2066690890).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * ListWorkflows lista workflows disponiveis.
 * @returns {$CancellablePromise<adapter$0.WorkflowSummary[]>}
 */
export function ListWorkflows() {
    return $Call.ByID(718136770).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * LoadWorkflow carrega um workflow por path.
 * @param {string} path
 * @returns {$CancellablePromise<adapter$0.LoadedWorkflow>}
 */
export function LoadWorkflow(path) {
    return $Call.ByID(2562520137, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * OpenPath abre um path no gerenciador de arquivos do SO.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenPath(path) {
    return $Call.ByID(1563167039, path);
}

/**
 * ResolveInput resolve inputs contra as definicoes do workflow.
 * @param {string} path
 * @param {{ [_ in string]?: any }} inputs
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function ResolveInput(path, inputs) {
    return $Call.ByID(818867136, path, inputs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * RunWorkflow inicia uma execucao de workflow.
 * @param {adapter$0.RunWorkflowRequest} req
 * @returns {$CancellablePromise<adapter$0.RunSummary>}
 */
export function RunWorkflow(req) {
    return $Call.ByID(2860720856, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SaveInput salva um arquivo de input.
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveInput(path, content) {
    return $Call.ByID(940574243, path, content);
}

/**
 * SaveWorkflow salva um arquivo de workflow.
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveWorkflow(path, content) {
    return $Call.ByID(2371325952, path, content);
}

/**
 * UpdateAppSettings atualiza as configuracoes locais.
 * @param {adapter$0.AppSettings} settings
 * @returns {$CancellablePromise<void>}
 */
export function UpdateAppSettings(settings) {
    return $Call.ByID(3882091533, settings);
}

/**
 * ValidateWorkflow valida um workflow.
 * @param {string} path
 * @returns {$CancellablePromise<adapter$0.ValidationResult>}
 */
export function ValidateWorkflow(path) {
    return $Call.ByID(2116615735, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

// Private type creation functions
const $$createType0 = adapter$0.RunSummary.createFrom;
const $$createType1 = adapter$0.DryRunResult.createFrom;
const $$createType2 = adapter$0.GraphResult.createFrom;
const $$createType3 = adapter$0.AppSettings.createFrom;
const $$createType4 = adapter$0.ArtifactResponse.createFrom;
const $$createType5 = adapter$0.ArtifactsResponse.createFrom;
const $$createType6 = adapter$0.EventsResponse.createFrom;
const $$createType7 = adapter$0.LogsResponse.createFrom;
const $$createType8 = adapter$0.NodeResponse.createFrom;
const $$createType9 = adapter$0.NodesResponse.createFrom;
const $$createType10 = adapter$0.PlanResponse.createFrom;
const $$createType11 = $models.HealthResponse.createFrom;
const $$createType12 = adapter$0.ListRunsResponse.createFrom;
const $$createType13 = adapter$0.WorkflowSummary.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = adapter$0.LoadedWorkflow.createFrom;
const $$createType16 = $Create.Map($Create.Any, $Create.Any);
const $$createType17 = adapter$0.ValidationResult.createFrom;
